// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bresenham.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bresenham::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bresenham::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> bresenham::ap_ST_fsm_state1 = "1";
const sc_lv<3> bresenham::ap_ST_fsm_state2 = "10";
const sc_lv<3> bresenham::ap_ST_fsm_state3 = "100";
const sc_lv<32> bresenham::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> bresenham::ap_const_lv32_1 = "1";
const sc_lv<32> bresenham::ap_const_lv32_2 = "10";
const sc_lv<1> bresenham::ap_const_lv1_0 = "0";
const sc_lv<32> bresenham::ap_const_lv32_1F = "11111";
const sc_lv<1> bresenham::ap_const_lv1_1 = "1";
const bool bresenham::ap_const_boolean_1 = true;

bresenham::bresenham(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );

    SC_METHOD(thread_m_new_fu_100_p2);
    sensitive << ( tmp_reg_186 );

    SC_METHOD(thread_slope_error_new_1_fu_158_p3);
    sensitive << ( slope_error_new_2_fu_134_p2 );
    sensitive << ( tmp_6_fu_139_p3 );
    sensitive << ( slope_error_new_3_fu_153_p2 );

    SC_METHOD(thread_slope_error_new_2_fu_134_p2);
    sensitive << ( m_new_reg_201 );
    sensitive << ( slope_error_new1_reg_66 );

    SC_METHOD(thread_slope_error_new_3_fu_153_p2);
    sensitive << ( tmp_4_reg_211 );
    sensitive << ( slope_error_new_2_fu_134_p2 );

    SC_METHOD(thread_slope_error_new_fu_111_p2);
    sensitive << ( m_new_fu_100_p2 );
    sensitive << ( tmp_1_fu_105_p2 );

    SC_METHOD(thread_tmp_1_fu_105_p2);
    sensitive << ( x0 );
    sensitive << ( x1 );

    SC_METHOD(thread_tmp_3_fu_117_p2);
    sensitive << ( x0 );
    sensitive << ( x1 );

    SC_METHOD(thread_tmp_4_fu_123_p2);
    sensitive << ( tmp_3_fu_117_p2 );

    SC_METHOD(thread_tmp_5_fu_129_p2);
    sensitive << ( x1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( x_reg_75 );

    SC_METHOD(thread_tmp_6_fu_139_p3);
    sensitive << ( slope_error_new_2_fu_134_p2 );

    SC_METHOD(thread_tmp_fu_94_p2);
    sensitive << ( y0 );
    sensitive << ( y1 );

    SC_METHOD(thread_x_1_fu_175_p2);
    sensitive << ( x_reg_75 );

    SC_METHOD(thread_xp);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );
    sensitive << ( x_reg_75 );

    SC_METHOD(thread_xp_ap_vld);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );

    SC_METHOD(thread_y_1_fu_166_p3);
    sensitive << ( y_reg_85 );
    sensitive << ( tmp_6_fu_139_p3 );
    sensitive << ( y_2_fu_147_p2 );

    SC_METHOD(thread_y_2_fu_147_p2);
    sensitive << ( y_reg_85 );

    SC_METHOD(thread_yp);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );
    sensitive << ( y_reg_85 );
    sensitive << ( tmp_6_fu_139_p3 );
    sensitive << ( y_2_fu_147_p2 );

    SC_METHOD(thread_yp_ap_vld);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_5_fu_129_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bresenham_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x0, "(port)x0");
    sc_trace(mVcdFile, y0, "(port)y0");
    sc_trace(mVcdFile, x1, "(port)x1");
    sc_trace(mVcdFile, y1, "(port)y1");
    sc_trace(mVcdFile, xp, "(port)xp");
    sc_trace(mVcdFile, xp_ap_vld, "(port)xp_ap_vld");
    sc_trace(mVcdFile, yp, "(port)yp");
    sc_trace(mVcdFile, yp_ap_vld, "(port)yp_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_fu_94_p2, "tmp_fu_94_p2");
    sc_trace(mVcdFile, tmp_reg_186, "tmp_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, m_new_fu_100_p2, "m_new_fu_100_p2");
    sc_trace(mVcdFile, m_new_reg_201, "m_new_reg_201");
    sc_trace(mVcdFile, slope_error_new_fu_111_p2, "slope_error_new_fu_111_p2");
    sc_trace(mVcdFile, tmp_4_fu_123_p2, "tmp_4_fu_123_p2");
    sc_trace(mVcdFile, tmp_4_reg_211, "tmp_4_reg_211");
    sc_trace(mVcdFile, slope_error_new_1_fu_158_p3, "slope_error_new_1_fu_158_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_5_fu_129_p2, "tmp_5_fu_129_p2");
    sc_trace(mVcdFile, y_1_fu_166_p3, "y_1_fu_166_p3");
    sc_trace(mVcdFile, x_1_fu_175_p2, "x_1_fu_175_p2");
    sc_trace(mVcdFile, slope_error_new1_reg_66, "slope_error_new1_reg_66");
    sc_trace(mVcdFile, x_reg_75, "x_reg_75");
    sc_trace(mVcdFile, y_reg_85, "y_reg_85");
    sc_trace(mVcdFile, tmp_1_fu_105_p2, "tmp_1_fu_105_p2");
    sc_trace(mVcdFile, tmp_3_fu_117_p2, "tmp_3_fu_117_p2");
    sc_trace(mVcdFile, slope_error_new_2_fu_134_p2, "slope_error_new_2_fu_134_p2");
    sc_trace(mVcdFile, tmp_6_fu_139_p3, "tmp_6_fu_139_p3");
    sc_trace(mVcdFile, slope_error_new_3_fu_153_p2, "slope_error_new_3_fu_153_p2");
    sc_trace(mVcdFile, y_2_fu_147_p2, "y_2_fu_147_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("bresenham.hdltvin.dat");
    mHdltvoutHandle.open("bresenham.hdltvout.dat");
}

bresenham::~bresenham() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void bresenham::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        slope_error_new1_reg_66 = slope_error_new_1_fu_158_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        slope_error_new1_reg_66 = slope_error_new_fu_111_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        x_reg_75 = x_1_fu_175_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_reg_75 = x0.read();
    }
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        y_reg_85 = y_1_fu_166_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        y_reg_85 = y0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        m_new_reg_201 = m_new_fu_100_p2.read();
        tmp_4_reg_211 = tmp_4_fu_123_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_reg_186 = tmp_fu_94_p2.read();
    }
}

void bresenham::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void bresenham::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void bresenham::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void bresenham::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bresenham::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bresenham::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bresenham::thread_m_new_fu_100_p2() {
    m_new_fu_100_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): tmp_reg_186.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void bresenham::thread_slope_error_new_1_fu_158_p3() {
    slope_error_new_1_fu_158_p3 = (!tmp_6_fu_139_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_6_fu_139_p3.read()[0].to_bool())? slope_error_new_2_fu_134_p2.read(): slope_error_new_3_fu_153_p2.read());
}

void bresenham::thread_slope_error_new_2_fu_134_p2() {
    slope_error_new_2_fu_134_p2 = (!slope_error_new1_reg_66.read().is_01() || !m_new_reg_201.read().is_01())? sc_lv<32>(): (sc_biguint<32>(slope_error_new1_reg_66.read()) + sc_biguint<32>(m_new_reg_201.read()));
}

void bresenham::thread_slope_error_new_3_fu_153_p2() {
    slope_error_new_3_fu_153_p2 = (!slope_error_new_2_fu_134_p2.read().is_01() || !tmp_4_reg_211.read().is_01())? sc_lv<32>(): (sc_biguint<32>(slope_error_new_2_fu_134_p2.read()) - sc_biguint<32>(tmp_4_reg_211.read()));
}

void bresenham::thread_slope_error_new_fu_111_p2() {
    slope_error_new_fu_111_p2 = (!tmp_1_fu_105_p2.read().is_01() || !m_new_fu_100_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_1_fu_105_p2.read()) + sc_biguint<32>(m_new_fu_100_p2.read()));
}

void bresenham::thread_tmp_1_fu_105_p2() {
    tmp_1_fu_105_p2 = (!x0.read().is_01() || !x1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(x0.read()) - sc_biguint<32>(x1.read()));
}

void bresenham::thread_tmp_3_fu_117_p2() {
    tmp_3_fu_117_p2 = (!x1.read().is_01() || !x0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(x1.read()) - sc_biguint<32>(x0.read()));
}

void bresenham::thread_tmp_4_fu_123_p2() {
    tmp_4_fu_123_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): tmp_3_fu_117_p2.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void bresenham::thread_tmp_5_fu_129_p2() {
    tmp_5_fu_129_p2 = (!x_reg_75.read().is_01() || !x1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(x_reg_75.read()) > sc_bigint<32>(x1.read()));
}

void bresenham::thread_tmp_6_fu_139_p3() {
    tmp_6_fu_139_p3 = slope_error_new_2_fu_134_p2.read().range(31, 31);
}

void bresenham::thread_tmp_fu_94_p2() {
    tmp_fu_94_p2 = (!y1.read().is_01() || !y0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(y1.read()) - sc_biguint<32>(y0.read()));
}

void bresenham::thread_x_1_fu_175_p2() {
    x_1_fu_175_p2 = (!x_reg_75.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(x_reg_75.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void bresenham::thread_xp() {
    xp = x_reg_75.read();
}

void bresenham::thread_xp_ap_vld() {
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        xp_ap_vld = ap_const_logic_1;
    } else {
        xp_ap_vld = ap_const_logic_0;
    }
}

void bresenham::thread_y_1_fu_166_p3() {
    y_1_fu_166_p3 = (!tmp_6_fu_139_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_6_fu_139_p3.read()[0].to_bool())? y_reg_85.read(): y_2_fu_147_p2.read());
}

void bresenham::thread_y_2_fu_147_p2() {
    y_2_fu_147_p2 = (!y_reg_85.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(y_reg_85.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void bresenham::thread_yp() {
    yp = (!tmp_6_fu_139_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_6_fu_139_p3.read()[0].to_bool())? y_reg_85.read(): y_2_fu_147_p2.read());
}

void bresenham::thread_yp_ap_vld() {
    if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        yp_ap_vld = ap_const_logic_1;
    } else {
        yp_ap_vld = ap_const_logic_0;
    }
}

void bresenham::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(tmp_5_fu_129_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void bresenham::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x0\" :  \"" << x0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"y0\" :  \"" << y0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x1\" :  \"" << x1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"y1\" :  \"" << y1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xp\" :  \"" << xp.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xp_ap_vld\" :  \"" << xp_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"yp\" :  \"" << yp.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"yp_ap_vld\" :  \"" << yp_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

