// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "x0"
#define AUTOTB_TVIN_x0  "../tv/cdatafile/c.bresenham.autotvin_x0.dat"
// wrapc file define: "y0"
#define AUTOTB_TVIN_y0  "../tv/cdatafile/c.bresenham.autotvin_y0.dat"
// wrapc file define: "x1"
#define AUTOTB_TVIN_x1  "../tv/cdatafile/c.bresenham.autotvin_x1.dat"
// wrapc file define: "y1"
#define AUTOTB_TVIN_y1  "../tv/cdatafile/c.bresenham.autotvin_y1.dat"
// wrapc file define: "xp"
#define AUTOTB_TVOUT_xp  "../tv/cdatafile/c.bresenham.autotvout_xp.dat"
// wrapc file define: "yp"
#define AUTOTB_TVOUT_yp  "../tv/cdatafile/c.bresenham.autotvout_yp.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "xp"
#define AUTOTB_TVOUT_PC_xp  "../tv/rtldatafile/rtl.bresenham.autotvout_xp.dat"
// tvout file define: "yp"
#define AUTOTB_TVOUT_PC_yp  "../tv/rtldatafile/rtl.bresenham.autotvout_yp.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			x0_depth = 0;
			y0_depth = 0;
			x1_depth = 0;
			y1_depth = 0;
			xp_depth = 0;
			yp_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{x0 " << x0_depth << "}\n";
			total_list << "{y0 " << y0_depth << "}\n";
			total_list << "{x1 " << x1_depth << "}\n";
			total_list << "{y1 " << y1_depth << "}\n";
			total_list << "{xp " << xp_depth << "}\n";
			total_list << "{yp " << yp_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int x0_depth;
		int y0_depth;
		int x1_depth;
		int y1_depth;
		int xp_depth;
		int yp_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void bresenham (
int x0,
int y0,
int x1,
int y1,
int* xp,
int* yp);

void AESL_WRAP_bresenham (
int x0,
int y0,
int x1,
int y1,
int* xp,
int* yp)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "xp"
		aesl_fh.read(AUTOTB_TVOUT_PC_xp, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_xp, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_xp, AESL_token); // data

			sc_bv<32> *xp_pc_buffer = new sc_bv<32>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'xp', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'xp', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					xp_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_xp, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_xp))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: xp
				{
					// bitslice(31, 0)
					// {
						// celement: xp(31, 0)
						// {
							sc_lv<32>* xp_lv0_0_0_1 = new sc_lv<32>[1];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: xp(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(xp[0]) != NULL) // check the null address if the c port is array or others
								{
									xp_lv0_0_0_1[hls_map_index].range(31, 0) = sc_bv<32>(xp_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: xp(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : xp[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : xp[0]
								// output_left_conversion : xp[i_0]
								// output_type_conversion : (xp_lv0_0_0_1[hls_map_index]).to_uint64()
								if (&(xp[0]) != NULL) // check the null address if the c port is array or others
								{
									xp[i_0] = (xp_lv0_0_0_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] xp_pc_buffer;
		}

		// output port post check: "yp"
		aesl_fh.read(AUTOTB_TVOUT_PC_yp, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_yp, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_yp, AESL_token); // data

			sc_bv<32> *yp_pc_buffer = new sc_bv<32>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'yp', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'yp', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					yp_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_yp, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_yp))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: yp
				{
					// bitslice(31, 0)
					// {
						// celement: yp(31, 0)
						// {
							sc_lv<32>* yp_lv0_0_0_1 = new sc_lv<32>[1];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: yp(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(yp[0]) != NULL) // check the null address if the c port is array or others
								{
									yp_lv0_0_0_1[hls_map_index].range(31, 0) = sc_bv<32>(yp_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: yp(31, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : yp[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : yp[0]
								// output_left_conversion : yp[i_0]
								// output_type_conversion : (yp_lv0_0_0_1[hls_map_index]).to_uint64()
								if (&(yp[0]) != NULL) // check the null address if the c port is array or others
								{
									yp[i_0] = (yp_lv0_0_0_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] yp_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "x0"
		char* tvin_x0 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_x0);

		// "y0"
		char* tvin_y0 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_y0);

		// "x1"
		char* tvin_x1 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_x1);

		// "y1"
		char* tvin_y1 = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_y1);

		// "xp"
		char* tvout_xp = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_xp);

		// "yp"
		char* tvout_yp = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_yp);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_x0, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_x0, tvin_x0);

		sc_bv<32> x0_tvin_wrapc_buffer;

		// RTL Name: x0
		{
			// bitslice(31, 0)
			{
				// celement: x0(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : x0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : x0
						// regulate_c_name       : x0
						// input_type_conversion : x0
						if (&(x0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> x0_tmp_mem;
							x0_tmp_mem = x0;
							x0_tvin_wrapc_buffer.range(31, 0) = x0_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_x0, "%s\n", (x0_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_x0, tvin_x0);
		}

		tcl_file.set_num(1, &tcl_file.x0_depth);
		sprintf(tvin_x0, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_x0, tvin_x0);

		// [[transaction]]
		sprintf(tvin_y0, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_y0, tvin_y0);

		sc_bv<32> y0_tvin_wrapc_buffer;

		// RTL Name: y0
		{
			// bitslice(31, 0)
			{
				// celement: y0(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : y0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : y0
						// regulate_c_name       : y0
						// input_type_conversion : y0
						if (&(y0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> y0_tmp_mem;
							y0_tmp_mem = y0;
							y0_tvin_wrapc_buffer.range(31, 0) = y0_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_y0, "%s\n", (y0_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_y0, tvin_y0);
		}

		tcl_file.set_num(1, &tcl_file.y0_depth);
		sprintf(tvin_y0, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_y0, tvin_y0);

		// [[transaction]]
		sprintf(tvin_x1, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_x1, tvin_x1);

		sc_bv<32> x1_tvin_wrapc_buffer;

		// RTL Name: x1
		{
			// bitslice(31, 0)
			{
				// celement: x1(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : x1
						// sub_1st_elem          : 
						// ori_name_1st_elem     : x1
						// regulate_c_name       : x1
						// input_type_conversion : x1
						if (&(x1) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> x1_tmp_mem;
							x1_tmp_mem = x1;
							x1_tvin_wrapc_buffer.range(31, 0) = x1_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_x1, "%s\n", (x1_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_x1, tvin_x1);
		}

		tcl_file.set_num(1, &tcl_file.x1_depth);
		sprintf(tvin_x1, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_x1, tvin_x1);

		// [[transaction]]
		sprintf(tvin_y1, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_y1, tvin_y1);

		sc_bv<32> y1_tvin_wrapc_buffer;

		// RTL Name: y1
		{
			// bitslice(31, 0)
			{
				// celement: y1(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : y1
						// sub_1st_elem          : 
						// ori_name_1st_elem     : y1
						// regulate_c_name       : y1
						// input_type_conversion : y1
						if (&(y1) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> y1_tmp_mem;
							y1_tmp_mem = y1;
							y1_tvin_wrapc_buffer.range(31, 0) = y1_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_y1, "%s\n", (y1_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_y1, tvin_y1);
		}

		tcl_file.set_num(1, &tcl_file.y1_depth);
		sprintf(tvin_y1, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_y1, tvin_y1);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		bresenham(x0, y0, x1, y1, xp, yp);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_xp, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_xp, tvout_xp);

		sc_bv<32>* xp_tvout_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: xp
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: xp(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : xp[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : xp[0]
						// regulate_c_name       : xp
						// input_type_conversion : xp[i_0]
						if (&(xp[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> xp_tmp_mem;
							xp_tmp_mem = xp[i_0];
							xp_tvout_wrapc_buffer[hls_map_index].range(31, 0) = xp_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_xp, "%s\n", (xp_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_xp, tvout_xp);
		}

		tcl_file.set_num(1, &tcl_file.xp_depth);
		sprintf(tvout_xp, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_xp, tvout_xp);

		// release memory allocation
		delete [] xp_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_yp, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_yp, tvout_yp);

		sc_bv<32>* yp_tvout_wrapc_buffer = new sc_bv<32>[1];

		// RTL Name: yp
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: yp(31, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : yp[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : yp[0]
						// regulate_c_name       : yp
						// input_type_conversion : yp[i_0]
						if (&(yp[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> yp_tmp_mem;
							yp_tmp_mem = yp[i_0];
							yp_tvout_wrapc_buffer[hls_map_index].range(31, 0) = yp_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_yp, "%s\n", (yp_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_yp, tvout_yp);
		}

		tcl_file.set_num(1, &tcl_file.yp_depth);
		sprintf(tvout_yp, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_yp, tvout_yp);

		// release memory allocation
		delete [] yp_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "x0"
		delete [] tvin_x0;
		// release memory allocation: "y0"
		delete [] tvin_y0;
		// release memory allocation: "x1"
		delete [] tvin_x1;
		// release memory allocation: "y1"
		delete [] tvin_y1;
		// release memory allocation: "xp"
		delete [] tvout_xp;
		// release memory allocation: "yp"
		delete [] tvout_yp;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

