// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dda.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dda::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dda::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<28> dda::ap_ST_fsm_state1 = "1";
const sc_lv<28> dda::ap_ST_fsm_state2 = "10";
const sc_lv<28> dda::ap_ST_fsm_state3 = "100";
const sc_lv<28> dda::ap_ST_fsm_state4 = "1000";
const sc_lv<28> dda::ap_ST_fsm_state5 = "10000";
const sc_lv<28> dda::ap_ST_fsm_state6 = "100000";
const sc_lv<28> dda::ap_ST_fsm_state7 = "1000000";
const sc_lv<28> dda::ap_ST_fsm_state8 = "10000000";
const sc_lv<28> dda::ap_ST_fsm_state9 = "100000000";
const sc_lv<28> dda::ap_ST_fsm_state10 = "1000000000";
const sc_lv<28> dda::ap_ST_fsm_state11 = "10000000000";
const sc_lv<28> dda::ap_ST_fsm_state12 = "100000000000";
const sc_lv<28> dda::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<28> dda::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<28> dda::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<28> dda::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<28> dda::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<32> dda::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dda::ap_const_lv32_19 = "11001";
const sc_lv<1> dda::ap_const_lv1_1 = "1";
const sc_lv<1> dda::ap_const_lv1_0 = "0";
const sc_lv<32> dda::ap_const_lv32_1 = "1";
const sc_lv<32> dda::ap_const_lv32_6 = "110";
const sc_lv<32> dda::ap_const_lv32_11 = "10001";
const sc_lv<32> dda::ap_const_lv32_12 = "10010";
const sc_lv<32> dda::ap_const_lv32_13 = "10011";
const sc_lv<32> dda::ap_const_lv32_17 = "10111";
const sc_lv<32> dda::ap_const_lv32_1A = "11010";
const sc_lv<32> dda::ap_const_lv32_1B = "11011";
const sc_lv<32> dda::ap_const_lv32_7 = "111";
const sc_lv<32> dda::ap_const_lv32_2 = "10";
const sc_lv<32> dda::ap_const_lv32_D = "1101";
const sc_lv<64> dda::ap_const_lv64_BFE0000000000000 = "1011111111100000000000000000000000000000000000000000000000000000";
const sc_lv<64> dda::ap_const_lv64_3FE0000000000000 = "11111111100000000000000000000000000000000000000000000000000000";
const sc_lv<32> dda::ap_const_lv32_14 = "10100";
const sc_lv<32> dda::ap_const_lv32_1E = "11110";
const sc_lv<8> dda::ap_const_lv8_FF = "11111111";
const sc_lv<23> dda::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> dda::ap_const_lv32_34 = "110100";
const sc_lv<32> dda::ap_const_lv32_3E = "111110";
const sc_lv<12> dda::ap_const_lv12_C01 = "110000000001";
const sc_lv<32> dda::ap_const_lv32_B = "1011";
const sc_lv<11> dda::ap_const_lv11_3FF = "1111111111";
const sc_lv<32> dda::ap_const_lv32_35 = "110101";
const sc_lv<32> dda::ap_const_lv32_54 = "1010100";
const sc_lv<32> dda::ap_const_lv32_3F = "111111";
const sc_lv<5> dda::ap_const_lv5_4 = "100";
const bool dda::ap_const_boolean_1 = true;

dda::dda(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dda_fadd_32ns_32nbkb_U1 = new dda_fadd_32ns_32nbkb<1,5,32,32,32>("dda_fadd_32ns_32nbkb_U1");
    dda_fadd_32ns_32nbkb_U1->clk(ap_clk);
    dda_fadd_32ns_32nbkb_U1->reset(ap_rst);
    dda_fadd_32ns_32nbkb_U1->din0(x_assign_reg_112);
    dda_fadd_32ns_32nbkb_U1->din1(Xinc_reg_1003);
    dda_fadd_32ns_32nbkb_U1->ce(ap_var_for_const0);
    dda_fadd_32ns_32nbkb_U1->dout(grp_fu_143_p2);
    dda_fadd_32ns_32nbkb_U2 = new dda_fadd_32ns_32nbkb<1,5,32,32,32>("dda_fadd_32ns_32nbkb_U2");
    dda_fadd_32ns_32nbkb_U2->clk(ap_clk);
    dda_fadd_32ns_32nbkb_U2->reset(ap_rst);
    dda_fadd_32ns_32nbkb_U2->din0(x_assign_3_reg_122);
    dda_fadd_32ns_32nbkb_U2->din1(Yinc_reg_1008);
    dda_fadd_32ns_32nbkb_U2->ce(ap_var_for_const0);
    dda_fadd_32ns_32nbkb_U2->dout(grp_fu_148_p2);
    dda_fdiv_32ns_32ncud_U3 = new dda_fdiv_32ns_32ncud<1,12,32,32,32>("dda_fdiv_32ns_32ncud_U3");
    dda_fdiv_32ns_32ncud_U3->clk(ap_clk);
    dda_fdiv_32ns_32ncud_U3->reset(ap_rst);
    dda_fdiv_32ns_32ncud_U3->din0(tmp_6_reg_977);
    dda_fdiv_32ns_32ncud_U3->din1(tmp_7_reg_982);
    dda_fdiv_32ns_32ncud_U3->ce(ap_var_for_const0);
    dda_fdiv_32ns_32ncud_U3->dout(grp_fu_153_p2);
    dda_fdiv_32ns_32ncud_U4 = new dda_fdiv_32ns_32ncud<1,12,32,32,32>("dda_fdiv_32ns_32ncud_U4");
    dda_fdiv_32ns_32ncud_U4->clk(ap_clk);
    dda_fdiv_32ns_32ncud_U4->reset(ap_rst);
    dda_fdiv_32ns_32ncud_U4->din0(tmp_8_reg_988);
    dda_fdiv_32ns_32ncud_U4->din1(tmp_7_reg_982);
    dda_fdiv_32ns_32ncud_U4->ce(ap_var_for_const0);
    dda_fdiv_32ns_32ncud_U4->dout(grp_fu_157_p2);
    dda_sitofp_32ns_3dEe_U5 = new dda_sitofp_32ns_3dEe<1,5,32,32>("dda_sitofp_32ns_3dEe_U5");
    dda_sitofp_32ns_3dEe_U5->clk(ap_clk);
    dda_sitofp_32ns_3dEe_U5->reset(ap_rst);
    dda_sitofp_32ns_3dEe_U5->din0(grp_fu_161_p0);
    dda_sitofp_32ns_3dEe_U5->ce(ap_var_for_const0);
    dda_sitofp_32ns_3dEe_U5->dout(grp_fu_161_p1);
    dda_sitofp_32ns_3dEe_U6 = new dda_sitofp_32ns_3dEe<1,5,32,32>("dda_sitofp_32ns_3dEe_U6");
    dda_sitofp_32ns_3dEe_U6->clk(ap_clk);
    dda_sitofp_32ns_3dEe_U6->reset(ap_rst);
    dda_sitofp_32ns_3dEe_U6->din0(grp_fu_164_p0);
    dda_sitofp_32ns_3dEe_U6->ce(ap_var_for_const0);
    dda_sitofp_32ns_3dEe_U6->dout(grp_fu_164_p1);
    dda_sitofp_32ns_3dEe_U7 = new dda_sitofp_32ns_3dEe<1,5,32,32>("dda_sitofp_32ns_3dEe_U7");
    dda_sitofp_32ns_3dEe_U7->clk(ap_clk);
    dda_sitofp_32ns_3dEe_U7->reset(ap_rst);
    dda_sitofp_32ns_3dEe_U7->din0(dy_reg_963);
    dda_sitofp_32ns_3dEe_U7->ce(ap_var_for_const0);
    dda_sitofp_32ns_3dEe_U7->dout(grp_fu_167_p1);
    dda_fpext_32ns_64eOg_U8 = new dda_fpext_32ns_64eOg<1,1,32,64>("dda_fpext_32ns_64eOg_U8");
    dda_fpext_32ns_64eOg_U8->din0(x_assign_reg_112);
    dda_fpext_32ns_64eOg_U8->dout(tmp_1_i_fu_170_p1);
    dda_fpext_32ns_64eOg_U9 = new dda_fpext_32ns_64eOg<1,1,32,64>("dda_fpext_32ns_64eOg_U9");
    dda_fpext_32ns_64eOg_U9->din0(x_assign_3_reg_122);
    dda_fpext_32ns_64eOg_U9->dout(tmp_1_i4_fu_174_p1);
    dda_fcmp_32ns_32nfYi_U10 = new dda_fcmp_32ns_32nfYi<1,1,32,32,1>("dda_fcmp_32ns_32nfYi_U10");
    dda_fcmp_32ns_32nfYi_U10->din0(x_assign_reg_112);
    dda_fcmp_32ns_32nfYi_U10->din1(ap_var_for_const1);
    dda_fcmp_32ns_32nfYi_U10->opcode(ap_var_for_const2);
    dda_fcmp_32ns_32nfYi_U10->dout(tmp_3_fu_178_p2);
    dda_fcmp_32ns_32nfYi_U11 = new dda_fcmp_32ns_32nfYi<1,1,32,32,1>("dda_fcmp_32ns_32nfYi_U11");
    dda_fcmp_32ns_32nfYi_U11->din0(x_assign_3_reg_122);
    dda_fcmp_32ns_32nfYi_U11->din1(ap_var_for_const1);
    dda_fcmp_32ns_32nfYi_U11->opcode(ap_var_for_const2);
    dda_fcmp_32ns_32nfYi_U11->dout(tmp_12_fu_184_p2);
    dda_dadd_64ns_64ng8j_U12 = new dda_dadd_64ns_64ng8j<1,6,64,64,64>("dda_dadd_64ns_64ng8j_U12");
    dda_dadd_64ns_64ng8j_U12->clk(ap_clk);
    dda_dadd_64ns_64ng8j_U12->reset(ap_rst);
    dda_dadd_64ns_64ng8j_U12->din0(tmp_1_i_reg_1026);
    dda_dadd_64ns_64ng8j_U12->din1(grp_fu_190_p1);
    dda_dadd_64ns_64ng8j_U12->ce(ap_var_for_const0);
    dda_dadd_64ns_64ng8j_U12->dout(grp_fu_190_p2);
    dda_dadd_64ns_64ng8j_U13 = new dda_dadd_64ns_64ng8j<1,6,64,64,64>("dda_dadd_64ns_64ng8j_U13");
    dda_dadd_64ns_64ng8j_U13->clk(ap_clk);
    dda_dadd_64ns_64ng8j_U13->reset(ap_rst);
    dda_dadd_64ns_64ng8j_U13->din0(tmp_1_i4_reg_1036);
    dda_dadd_64ns_64ng8j_U13->din1(grp_fu_196_p1);
    dda_dadd_64ns_64ng8j_U13->ce(ap_var_for_const0);
    dda_dadd_64ns_64ng8j_U13->dout(grp_fu_196_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_X1_to_int_fu_281_p1);
    sensitive << ( x_assign_reg_112 );

    SC_METHOD(thread_Y1_to_int_fu_323_p1);
    sensitive << ( x_assign_3_reg_122 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );

    SC_METHOD(thread_dx_fu_210_p2);
    sensitive << ( x0 );
    sensitive << ( x1 );

    SC_METHOD(thread_dy_fu_216_p2);
    sensitive << ( y0 );
    sensitive << ( y1 );

    SC_METHOD(thread_grp_fu_161_p0);
    sensitive << ( x0 );
    sensitive << ( dx_reg_955 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_164_p0);
    sensitive << ( y0 );
    sensitive << ( steps_reg_971 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_190_p1);
    sensitive << ( tmp_4_reg_1021 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_grp_fu_196_p1);
    sensitive << ( tmp_13_reg_1031 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_i_1_fu_275_p2);
    sensitive << ( i_reg_132 );

    SC_METHOD(thread_isNeg_1_fu_529_p3);
    sensitive << ( sh_assign_2_fu_523_p2 );

    SC_METHOD(thread_isNeg_2_fu_651_p3);
    sensitive << ( sh_assign_4_fu_645_p2 );

    SC_METHOD(thread_isNeg_3_fu_773_p3);
    sensitive << ( sh_assign_6_fu_767_p2 );

    SC_METHOD(thread_isNeg_fu_407_p3);
    sensitive << ( sh_assign_fu_401_p2 );

    SC_METHOD(thread_loc_V_1_fu_379_p1);
    sensitive << ( p_Val2_s_fu_365_p1 );

    SC_METHOD(thread_loc_V_2_fu_491_p4);
    sensitive << ( p_Val2_5_fu_487_p1 );

    SC_METHOD(thread_loc_V_3_fu_501_p1);
    sensitive << ( p_Val2_5_fu_487_p1 );

    SC_METHOD(thread_loc_V_4_fu_613_p4);
    sensitive << ( p_Val2_10_fu_609_p1 );

    SC_METHOD(thread_loc_V_5_fu_623_p1);
    sensitive << ( p_Val2_10_fu_609_p1 );

    SC_METHOD(thread_loc_V_6_fu_735_p4);
    sensitive << ( p_Val2_15_fu_731_p1 );

    SC_METHOD(thread_loc_V_7_fu_745_p1);
    sensitive << ( p_Val2_15_fu_731_p1 );

    SC_METHOD(thread_loc_V_fu_369_p4);
    sensitive << ( p_Val2_s_fu_365_p1 );

    SC_METHOD(thread_n_assign_1_fu_232_p3);
    sensitive << ( dx_reg_955 );
    sensitive << ( tmp_i_fu_222_p2 );
    sensitive << ( tmp_i_8_fu_227_p2 );

    SC_METHOD(thread_n_assign_3_fu_249_p3);
    sensitive << ( dy_reg_963 );
    sensitive << ( tmp_i1_fu_239_p2 );
    sensitive << ( tmp_i2_fu_244_p2 );

    SC_METHOD(thread_notlhs1_fu_341_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );
    sensitive << ( tmp_s_fu_327_p4 );

    SC_METHOD(thread_notlhs_fu_299_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );
    sensitive << ( tmp_fu_285_p4 );

    SC_METHOD(thread_notrhs1_fu_347_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );
    sensitive << ( tmp_27_fu_337_p1 );

    SC_METHOD(thread_notrhs_fu_305_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );
    sensitive << ( tmp_1_fu_295_p1 );

    SC_METHOD(thread_p_Result_1_fu_872_p3);
    sensitive << ( p_Val2_5_reg_1062 );

    SC_METHOD(thread_p_Result_2_fu_899_p3);
    sensitive << ( p_Val2_10_reg_1073 );

    SC_METHOD(thread_p_Result_3_fu_918_p3);
    sensitive << ( p_Val2_15_reg_1084 );

    SC_METHOD(thread_p_Result_s_fu_853_p3);
    sensitive << ( p_Val2_s_reg_1051 );

    SC_METHOD(thread_p_Val2_10_fu_609_p1);
    sensitive << ( reg_206 );

    SC_METHOD(thread_p_Val2_12_fu_723_p3);
    sensitive << ( isNeg_2_fu_651_p3 );
    sensitive << ( tmp_17_fu_709_p1 );
    sensitive << ( tmp_19_fu_713_p4 );

    SC_METHOD(thread_p_Val2_14_fu_911_p3);
    sensitive << ( p_Val2_12_reg_1078 );
    sensitive << ( p_Result_2_fu_899_p3 );
    sensitive << ( p_Val2_6_i_i_i_i1_fu_906_p2 );

    SC_METHOD(thread_p_Val2_15_fu_731_p1);
    sensitive << ( reg_206 );

    SC_METHOD(thread_p_Val2_17_fu_845_p3);
    sensitive << ( isNeg_3_fu_773_p3 );
    sensitive << ( tmp_20_fu_831_p1 );
    sensitive << ( tmp_21_fu_835_p4 );

    SC_METHOD(thread_p_Val2_19_fu_930_p3);
    sensitive << ( p_Val2_17_reg_1089 );
    sensitive << ( p_Result_3_fu_918_p3 );
    sensitive << ( p_Val2_6_i_i_i1_i1_fu_925_p2 );

    SC_METHOD(thread_p_Val2_2_fu_479_p3);
    sensitive << ( isNeg_fu_407_p3 );
    sensitive << ( tmp_10_fu_465_p1 );
    sensitive << ( tmp_14_fu_469_p4 );

    SC_METHOD(thread_p_Val2_4_fu_865_p3);
    sensitive << ( p_Val2_2_reg_1056 );
    sensitive << ( p_Result_s_fu_853_p3 );
    sensitive << ( p_Val2_6_i_i_i_i_fu_860_p2 );

    SC_METHOD(thread_p_Val2_5_fu_487_p1);
    sensitive << ( reg_202 );

    SC_METHOD(thread_p_Val2_6_i_i_i1_i1_fu_925_p2);
    sensitive << ( p_Val2_17_reg_1089 );

    SC_METHOD(thread_p_Val2_6_i_i_i1_i_fu_879_p2);
    sensitive << ( p_Val2_7_reg_1067 );

    SC_METHOD(thread_p_Val2_6_i_i_i_i1_fu_906_p2);
    sensitive << ( p_Val2_12_reg_1078 );

    SC_METHOD(thread_p_Val2_6_i_i_i_i_fu_860_p2);
    sensitive << ( p_Val2_2_reg_1056 );

    SC_METHOD(thread_p_Val2_7_fu_601_p3);
    sensitive << ( isNeg_1_fu_529_p3 );
    sensitive << ( tmp_15_fu_587_p1 );
    sensitive << ( tmp_16_fu_591_p4 );

    SC_METHOD(thread_p_Val2_9_fu_884_p3);
    sensitive << ( p_Val2_7_reg_1067 );
    sensitive << ( p_Result_1_fu_872_p3 );
    sensitive << ( p_Val2_6_i_i_i1_i_fu_879_p2 );

    SC_METHOD(thread_p_Val2_s_fu_365_p1);
    sensitive << ( reg_202 );

    SC_METHOD(thread_sh_assign_1_fu_425_p3);
    sensitive << ( sh_assign_fu_401_p2 );
    sensitive << ( isNeg_fu_407_p3 );
    sensitive << ( tmp_9_i_i_i_i_cast_fu_421_p1 );

    SC_METHOD(thread_sh_assign_1_i17_cast_fu_677_p1);
    sensitive << ( sh_assign_5_fu_669_p3 );

    SC_METHOD(thread_sh_assign_1_i_cast_fu_433_p1);
    sensitive << ( sh_assign_1_fu_425_p3 );

    SC_METHOD(thread_sh_assign_2_fu_523_p2);
    sensitive << ( tmp_i_i_i_i8_i_cast_fu_519_p1 );

    SC_METHOD(thread_sh_assign_3_fu_547_p3);
    sensitive << ( sh_assign_2_fu_523_p2 );
    sensitive << ( isNeg_1_fu_529_p3 );
    sensitive << ( tmp_9_i_i_i1_i_cast_fu_543_p1 );

    SC_METHOD(thread_sh_assign_3_i38_cast_fu_799_p1);
    sensitive << ( sh_assign_7_fu_791_p3 );

    SC_METHOD(thread_sh_assign_3_i_cast_fu_555_p1);
    sensitive << ( sh_assign_3_fu_547_p3 );

    SC_METHOD(thread_sh_assign_4_fu_645_p2);
    sensitive << ( tmp_i_i_i_i_i13_cast_fu_641_p1 );

    SC_METHOD(thread_sh_assign_5_fu_669_p3);
    sensitive << ( sh_assign_4_fu_645_p2 );
    sensitive << ( isNeg_2_fu_651_p3 );
    sensitive << ( tmp_9_i_i_i_i16_cast_fu_665_p1 );

    SC_METHOD(thread_sh_assign_6_fu_767_p2);
    sensitive << ( tmp_i_i_i_i8_i34_cas_fu_763_p1 );

    SC_METHOD(thread_sh_assign_7_fu_791_p3);
    sensitive << ( sh_assign_6_fu_767_p2 );
    sensitive << ( isNeg_3_fu_773_p3 );
    sensitive << ( tmp_9_i_i_i1_i37_cas_fu_787_p1 );

    SC_METHOD(thread_sh_assign_fu_401_p2);
    sensitive << ( tmp_i_i_i_i_i_cast_fu_397_p1 );

    SC_METHOD(thread_steps_fu_262_p3);
    sensitive << ( n_assign_1_fu_232_p3 );
    sensitive << ( n_assign_3_fu_249_p3 );
    sensitive << ( tmp_5_fu_256_p2 );

    SC_METHOD(thread_tmp_10_fu_465_p1);
    sensitive << ( tmp_18_fu_457_p3 );

    SC_METHOD(thread_tmp_11_fu_353_p2);
    sensitive << ( notrhs1_fu_347_p2 );
    sensitive << ( notlhs1_fu_341_p2 );

    SC_METHOD(thread_tmp_13_fu_359_p2);
    sensitive << ( tmp_11_fu_353_p2 );
    sensitive << ( tmp_12_fu_184_p2 );

    SC_METHOD(thread_tmp_14_fu_469_p4);
    sensitive << ( tmp_3_i_i_i_i_fu_451_p2 );

    SC_METHOD(thread_tmp_15_fu_587_p1);
    sensitive << ( tmp_26_fu_579_p3 );

    SC_METHOD(thread_tmp_16_fu_591_p4);
    sensitive << ( tmp_3_i_i_i1_i_fu_573_p2 );

    SC_METHOD(thread_tmp_17_fu_709_p1);
    sensitive << ( tmp_33_fu_701_p3 );

    SC_METHOD(thread_tmp_18_fu_457_p3);
    sensitive << ( tmp_1_i_i_i_i_fu_445_p2 );

    SC_METHOD(thread_tmp_19_fu_713_p4);
    sensitive << ( tmp_3_i_i_i_i1_fu_695_p2 );

    SC_METHOD(thread_tmp_1_fu_295_p1);
    sensitive << ( X1_to_int_fu_281_p1 );

    SC_METHOD(thread_tmp_1_i_i_i1_i1_fu_811_p2);
    sensitive << ( tmp_7_i_i_i7_i1_fu_749_p4 );
    sensitive << ( tmp_i_i_i1_i39_cast_fu_807_p1 );

    SC_METHOD(thread_tmp_1_i_i_i1_i_fu_567_p2);
    sensitive << ( tmp_7_i_i_i7_i_fu_505_p4 );
    sensitive << ( tmp_i_i_i1_i_cast_fu_563_p1 );

    SC_METHOD(thread_tmp_1_i_i_i_i1_fu_689_p2);
    sensitive << ( tmp_7_i_i_i_i1_fu_627_p4 );
    sensitive << ( tmp_i_i_i_i18_cast_fu_685_p1 );

    SC_METHOD(thread_tmp_1_i_i_i_i_fu_445_p2);
    sensitive << ( tmp_7_i_i_i_i_fu_383_p4 );
    sensitive << ( tmp_i_i_i_i_cast_fu_441_p1 );

    SC_METHOD(thread_tmp_20_fu_831_p1);
    sensitive << ( tmp_37_fu_823_p3 );

    SC_METHOD(thread_tmp_21_fu_835_p4);
    sensitive << ( tmp_3_i_i_i1_i1_fu_817_p2 );

    SC_METHOD(thread_tmp_26_fu_579_p3);
    sensitive << ( tmp_1_i_i_i1_i_fu_567_p2 );

    SC_METHOD(thread_tmp_27_fu_337_p1);
    sensitive << ( Y1_to_int_fu_323_p1 );

    SC_METHOD(thread_tmp_2_fu_311_p2);
    sensitive << ( notrhs_fu_305_p2 );
    sensitive << ( notlhs_fu_299_p2 );

    SC_METHOD(thread_tmp_33_fu_701_p3);
    sensitive << ( tmp_1_i_i_i_i1_fu_689_p2 );

    SC_METHOD(thread_tmp_37_fu_823_p3);
    sensitive << ( tmp_1_i_i_i1_i1_fu_811_p2 );

    SC_METHOD(thread_tmp_3_i_i_i1_i1_fu_817_p2);
    sensitive << ( tmp_7_i_i_i7_i33_cas_fu_759_p1 );
    sensitive << ( tmp_i_i_i1_i1_fu_803_p1 );

    SC_METHOD(thread_tmp_3_i_i_i1_i_fu_573_p2);
    sensitive << ( tmp_7_i_i_i7_i_cast_fu_515_p1 );
    sensitive << ( tmp_i_i_i1_i_fu_559_p1 );

    SC_METHOD(thread_tmp_3_i_i_i_i1_fu_695_p2);
    sensitive << ( tmp_7_i_i_i_i12_cast_fu_637_p1 );
    sensitive << ( tmp_i_i_i_i1_fu_681_p1 );

    SC_METHOD(thread_tmp_3_i_i_i_i_fu_451_p2);
    sensitive << ( tmp_7_i_i_i_i_cast_fu_393_p1 );
    sensitive << ( tmp_i_i_i_i_fu_437_p1 );

    SC_METHOD(thread_tmp_4_fu_317_p2);
    sensitive << ( tmp_2_fu_311_p2 );
    sensitive << ( tmp_3_fu_178_p2 );

    SC_METHOD(thread_tmp_5_fu_256_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( n_assign_1_fu_232_p3 );
    sensitive << ( n_assign_3_fu_249_p3 );

    SC_METHOD(thread_tmp_7_i_i_i7_i1_fu_749_p4);
    sensitive << ( loc_V_7_fu_745_p1 );

    SC_METHOD(thread_tmp_7_i_i_i7_i33_cas_fu_759_p1);
    sensitive << ( tmp_7_i_i_i7_i1_fu_749_p4 );

    SC_METHOD(thread_tmp_7_i_i_i7_i_cast_fu_515_p1);
    sensitive << ( tmp_7_i_i_i7_i_fu_505_p4 );

    SC_METHOD(thread_tmp_7_i_i_i7_i_fu_505_p4);
    sensitive << ( loc_V_3_fu_501_p1 );

    SC_METHOD(thread_tmp_7_i_i_i_i12_cast_fu_637_p1);
    sensitive << ( tmp_7_i_i_i_i1_fu_627_p4 );

    SC_METHOD(thread_tmp_7_i_i_i_i1_fu_627_p4);
    sensitive << ( loc_V_5_fu_623_p1 );

    SC_METHOD(thread_tmp_7_i_i_i_i_cast_fu_393_p1);
    sensitive << ( tmp_7_i_i_i_i_fu_383_p4 );

    SC_METHOD(thread_tmp_7_i_i_i_i_fu_383_p4);
    sensitive << ( loc_V_1_fu_379_p1 );

    SC_METHOD(thread_tmp_9_fu_270_p2);
    sensitive << ( steps_reg_971 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( i_reg_132 );

    SC_METHOD(thread_tmp_9_i_i_i1_i1_fu_781_p2);
    sensitive << ( loc_V_6_fu_735_p4 );

    SC_METHOD(thread_tmp_9_i_i_i1_i37_cas_fu_787_p1);
    sensitive << ( tmp_9_i_i_i1_i1_fu_781_p2 );

    SC_METHOD(thread_tmp_9_i_i_i1_i_cast_fu_543_p1);
    sensitive << ( tmp_9_i_i_i1_i_fu_537_p2 );

    SC_METHOD(thread_tmp_9_i_i_i1_i_fu_537_p2);
    sensitive << ( loc_V_2_fu_491_p4 );

    SC_METHOD(thread_tmp_9_i_i_i_i16_cast_fu_665_p1);
    sensitive << ( tmp_9_i_i_i_i1_fu_659_p2 );

    SC_METHOD(thread_tmp_9_i_i_i_i1_fu_659_p2);
    sensitive << ( loc_V_4_fu_613_p4 );

    SC_METHOD(thread_tmp_9_i_i_i_i_cast_fu_421_p1);
    sensitive << ( tmp_9_i_i_i_i_fu_415_p2 );

    SC_METHOD(thread_tmp_9_i_i_i_i_fu_415_p2);
    sensitive << ( loc_V_fu_369_p4 );

    SC_METHOD(thread_tmp_fu_285_p4);
    sensitive << ( X1_to_int_fu_281_p1 );

    SC_METHOD(thread_tmp_i1_fu_239_p2);
    sensitive << ( dy_reg_963 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_i2_fu_244_p2);
    sensitive << ( dy_reg_963 );

    SC_METHOD(thread_tmp_i_8_fu_227_p2);
    sensitive << ( dx_reg_955 );

    SC_METHOD(thread_tmp_i_fu_222_p2);
    sensitive << ( dx_reg_955 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_i_i_i1_i1_fu_803_p1);
    sensitive << ( sh_assign_3_i38_cast_fu_799_p1 );

    SC_METHOD(thread_tmp_i_i_i1_i39_cast_fu_807_p1);
    sensitive << ( sh_assign_3_i38_cast_fu_799_p1 );

    SC_METHOD(thread_tmp_i_i_i1_i_cast_fu_563_p1);
    sensitive << ( sh_assign_3_i_cast_fu_555_p1 );

    SC_METHOD(thread_tmp_i_i_i1_i_fu_559_p1);
    sensitive << ( sh_assign_3_i_cast_fu_555_p1 );

    SC_METHOD(thread_tmp_i_i_i_i18_cast_fu_685_p1);
    sensitive << ( sh_assign_1_i17_cast_fu_677_p1 );

    SC_METHOD(thread_tmp_i_i_i_i1_fu_681_p1);
    sensitive << ( sh_assign_1_i17_cast_fu_677_p1 );

    SC_METHOD(thread_tmp_i_i_i_i8_i34_cas_fu_763_p1);
    sensitive << ( loc_V_6_fu_735_p4 );

    SC_METHOD(thread_tmp_i_i_i_i8_i_cast_fu_519_p1);
    sensitive << ( loc_V_2_fu_491_p4 );

    SC_METHOD(thread_tmp_i_i_i_i_cast_fu_441_p1);
    sensitive << ( sh_assign_1_i_cast_fu_433_p1 );

    SC_METHOD(thread_tmp_i_i_i_i_fu_437_p1);
    sensitive << ( sh_assign_1_i_cast_fu_433_p1 );

    SC_METHOD(thread_tmp_i_i_i_i_i13_cast_fu_641_p1);
    sensitive << ( loc_V_4_fu_613_p4 );

    SC_METHOD(thread_tmp_i_i_i_i_i_cast_fu_397_p1);
    sensitive << ( loc_V_fu_369_p4 );

    SC_METHOD(thread_tmp_s_fu_327_p4);
    sensitive << ( Y1_to_int_fu_323_p1 );

    SC_METHOD(thread_xp);
    sensitive << ( tmp_4_reg_1021 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( p_Val2_4_fu_865_p3 );
    sensitive << ( p_Val2_9_fu_884_p3 );

    SC_METHOD(thread_xp_ap_vld);
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_yp);
    sensitive << ( tmp_13_reg_1031 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( p_Val2_14_fu_911_p3 );
    sensitive << ( p_Val2_19_fu_930_p3 );

    SC_METHOD(thread_yp_ap_vld);
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_9_fu_270_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "0000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dda_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x0, "(port)x0");
    sc_trace(mVcdFile, y0, "(port)y0");
    sc_trace(mVcdFile, x1, "(port)x1");
    sc_trace(mVcdFile, y1, "(port)y1");
    sc_trace(mVcdFile, xp, "(port)xp");
    sc_trace(mVcdFile, xp_ap_vld, "(port)xp_ap_vld");
    sc_trace(mVcdFile, yp, "(port)yp");
    sc_trace(mVcdFile, yp_ap_vld, "(port)yp_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_190_p2, "grp_fu_190_p2");
    sc_trace(mVcdFile, reg_202, "reg_202");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, tmp_4_reg_1021, "tmp_4_reg_1021");
    sc_trace(mVcdFile, grp_fu_196_p2, "grp_fu_196_p2");
    sc_trace(mVcdFile, reg_206, "reg_206");
    sc_trace(mVcdFile, tmp_13_reg_1031, "tmp_13_reg_1031");
    sc_trace(mVcdFile, dx_fu_210_p2, "dx_fu_210_p2");
    sc_trace(mVcdFile, dx_reg_955, "dx_reg_955");
    sc_trace(mVcdFile, dy_fu_216_p2, "dy_fu_216_p2");
    sc_trace(mVcdFile, dy_reg_963, "dy_reg_963");
    sc_trace(mVcdFile, steps_fu_262_p3, "steps_fu_262_p3");
    sc_trace(mVcdFile, steps_reg_971, "steps_reg_971");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_fu_161_p1, "grp_fu_161_p1");
    sc_trace(mVcdFile, tmp_6_reg_977, "tmp_6_reg_977");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_164_p1, "grp_fu_164_p1");
    sc_trace(mVcdFile, tmp_7_reg_982, "tmp_7_reg_982");
    sc_trace(mVcdFile, grp_fu_167_p1, "grp_fu_167_p1");
    sc_trace(mVcdFile, tmp_8_reg_988, "tmp_8_reg_988");
    sc_trace(mVcdFile, X_reg_993, "X_reg_993");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, Y_reg_998, "Y_reg_998");
    sc_trace(mVcdFile, grp_fu_153_p2, "grp_fu_153_p2");
    sc_trace(mVcdFile, Xinc_reg_1003, "Xinc_reg_1003");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, grp_fu_157_p2, "grp_fu_157_p2");
    sc_trace(mVcdFile, Yinc_reg_1008, "Yinc_reg_1008");
    sc_trace(mVcdFile, i_1_fu_275_p2, "i_1_fu_275_p2");
    sc_trace(mVcdFile, i_1_reg_1016, "i_1_reg_1016");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, tmp_4_fu_317_p2, "tmp_4_fu_317_p2");
    sc_trace(mVcdFile, tmp_9_fu_270_p2, "tmp_9_fu_270_p2");
    sc_trace(mVcdFile, tmp_1_i_fu_170_p1, "tmp_1_i_fu_170_p1");
    sc_trace(mVcdFile, tmp_1_i_reg_1026, "tmp_1_i_reg_1026");
    sc_trace(mVcdFile, tmp_13_fu_359_p2, "tmp_13_fu_359_p2");
    sc_trace(mVcdFile, tmp_1_i4_fu_174_p1, "tmp_1_i4_fu_174_p1");
    sc_trace(mVcdFile, tmp_1_i4_reg_1036, "tmp_1_i4_reg_1036");
    sc_trace(mVcdFile, grp_fu_143_p2, "grp_fu_143_p2");
    sc_trace(mVcdFile, X_1_reg_1041, "X_1_reg_1041");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_148_p2, "grp_fu_148_p2");
    sc_trace(mVcdFile, Y_1_reg_1046, "Y_1_reg_1046");
    sc_trace(mVcdFile, p_Val2_s_fu_365_p1, "p_Val2_s_fu_365_p1");
    sc_trace(mVcdFile, p_Val2_s_reg_1051, "p_Val2_s_reg_1051");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, p_Val2_2_fu_479_p3, "p_Val2_2_fu_479_p3");
    sc_trace(mVcdFile, p_Val2_2_reg_1056, "p_Val2_2_reg_1056");
    sc_trace(mVcdFile, p_Val2_5_fu_487_p1, "p_Val2_5_fu_487_p1");
    sc_trace(mVcdFile, p_Val2_5_reg_1062, "p_Val2_5_reg_1062");
    sc_trace(mVcdFile, p_Val2_7_fu_601_p3, "p_Val2_7_fu_601_p3");
    sc_trace(mVcdFile, p_Val2_7_reg_1067, "p_Val2_7_reg_1067");
    sc_trace(mVcdFile, p_Val2_10_fu_609_p1, "p_Val2_10_fu_609_p1");
    sc_trace(mVcdFile, p_Val2_10_reg_1073, "p_Val2_10_reg_1073");
    sc_trace(mVcdFile, p_Val2_12_fu_723_p3, "p_Val2_12_fu_723_p3");
    sc_trace(mVcdFile, p_Val2_12_reg_1078, "p_Val2_12_reg_1078");
    sc_trace(mVcdFile, p_Val2_15_fu_731_p1, "p_Val2_15_fu_731_p1");
    sc_trace(mVcdFile, p_Val2_15_reg_1084, "p_Val2_15_reg_1084");
    sc_trace(mVcdFile, p_Val2_17_fu_845_p3, "p_Val2_17_fu_845_p3");
    sc_trace(mVcdFile, p_Val2_17_reg_1089, "p_Val2_17_reg_1089");
    sc_trace(mVcdFile, x_assign_reg_112, "x_assign_reg_112");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, x_assign_3_reg_122, "x_assign_3_reg_122");
    sc_trace(mVcdFile, i_reg_132, "i_reg_132");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_161_p0, "grp_fu_161_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_fu_164_p0, "grp_fu_164_p0");
    sc_trace(mVcdFile, grp_fu_190_p1, "grp_fu_190_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, grp_fu_196_p1, "grp_fu_196_p1");
    sc_trace(mVcdFile, tmp_i_fu_222_p2, "tmp_i_fu_222_p2");
    sc_trace(mVcdFile, tmp_i_8_fu_227_p2, "tmp_i_8_fu_227_p2");
    sc_trace(mVcdFile, tmp_i1_fu_239_p2, "tmp_i1_fu_239_p2");
    sc_trace(mVcdFile, tmp_i2_fu_244_p2, "tmp_i2_fu_244_p2");
    sc_trace(mVcdFile, n_assign_1_fu_232_p3, "n_assign_1_fu_232_p3");
    sc_trace(mVcdFile, n_assign_3_fu_249_p3, "n_assign_3_fu_249_p3");
    sc_trace(mVcdFile, tmp_5_fu_256_p2, "tmp_5_fu_256_p2");
    sc_trace(mVcdFile, X1_to_int_fu_281_p1, "X1_to_int_fu_281_p1");
    sc_trace(mVcdFile, tmp_fu_285_p4, "tmp_fu_285_p4");
    sc_trace(mVcdFile, tmp_1_fu_295_p1, "tmp_1_fu_295_p1");
    sc_trace(mVcdFile, notrhs_fu_305_p2, "notrhs_fu_305_p2");
    sc_trace(mVcdFile, notlhs_fu_299_p2, "notlhs_fu_299_p2");
    sc_trace(mVcdFile, tmp_2_fu_311_p2, "tmp_2_fu_311_p2");
    sc_trace(mVcdFile, tmp_3_fu_178_p2, "tmp_3_fu_178_p2");
    sc_trace(mVcdFile, Y1_to_int_fu_323_p1, "Y1_to_int_fu_323_p1");
    sc_trace(mVcdFile, tmp_s_fu_327_p4, "tmp_s_fu_327_p4");
    sc_trace(mVcdFile, tmp_27_fu_337_p1, "tmp_27_fu_337_p1");
    sc_trace(mVcdFile, notrhs1_fu_347_p2, "notrhs1_fu_347_p2");
    sc_trace(mVcdFile, notlhs1_fu_341_p2, "notlhs1_fu_341_p2");
    sc_trace(mVcdFile, tmp_11_fu_353_p2, "tmp_11_fu_353_p2");
    sc_trace(mVcdFile, tmp_12_fu_184_p2, "tmp_12_fu_184_p2");
    sc_trace(mVcdFile, loc_V_1_fu_379_p1, "loc_V_1_fu_379_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i_i_fu_383_p4, "tmp_7_i_i_i_i_fu_383_p4");
    sc_trace(mVcdFile, loc_V_fu_369_p4, "loc_V_fu_369_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i_i_cast_fu_397_p1, "tmp_i_i_i_i_i_cast_fu_397_p1");
    sc_trace(mVcdFile, sh_assign_fu_401_p2, "sh_assign_fu_401_p2");
    sc_trace(mVcdFile, tmp_9_i_i_i_i_fu_415_p2, "tmp_9_i_i_i_i_fu_415_p2");
    sc_trace(mVcdFile, isNeg_fu_407_p3, "isNeg_fu_407_p3");
    sc_trace(mVcdFile, tmp_9_i_i_i_i_cast_fu_421_p1, "tmp_9_i_i_i_i_cast_fu_421_p1");
    sc_trace(mVcdFile, sh_assign_1_fu_425_p3, "sh_assign_1_fu_425_p3");
    sc_trace(mVcdFile, sh_assign_1_i_cast_fu_433_p1, "sh_assign_1_i_cast_fu_433_p1");
    sc_trace(mVcdFile, tmp_i_i_i_i_cast_fu_441_p1, "tmp_i_i_i_i_cast_fu_441_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i_i_cast_fu_393_p1, "tmp_7_i_i_i_i_cast_fu_393_p1");
    sc_trace(mVcdFile, tmp_i_i_i_i_fu_437_p1, "tmp_i_i_i_i_fu_437_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i_i_fu_445_p2, "tmp_1_i_i_i_i_fu_445_p2");
    sc_trace(mVcdFile, tmp_18_fu_457_p3, "tmp_18_fu_457_p3");
    sc_trace(mVcdFile, tmp_3_i_i_i_i_fu_451_p2, "tmp_3_i_i_i_i_fu_451_p2");
    sc_trace(mVcdFile, tmp_10_fu_465_p1, "tmp_10_fu_465_p1");
    sc_trace(mVcdFile, tmp_14_fu_469_p4, "tmp_14_fu_469_p4");
    sc_trace(mVcdFile, loc_V_3_fu_501_p1, "loc_V_3_fu_501_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i7_i_fu_505_p4, "tmp_7_i_i_i7_i_fu_505_p4");
    sc_trace(mVcdFile, loc_V_2_fu_491_p4, "loc_V_2_fu_491_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i8_i_cast_fu_519_p1, "tmp_i_i_i_i8_i_cast_fu_519_p1");
    sc_trace(mVcdFile, sh_assign_2_fu_523_p2, "sh_assign_2_fu_523_p2");
    sc_trace(mVcdFile, tmp_9_i_i_i1_i_fu_537_p2, "tmp_9_i_i_i1_i_fu_537_p2");
    sc_trace(mVcdFile, isNeg_1_fu_529_p3, "isNeg_1_fu_529_p3");
    sc_trace(mVcdFile, tmp_9_i_i_i1_i_cast_fu_543_p1, "tmp_9_i_i_i1_i_cast_fu_543_p1");
    sc_trace(mVcdFile, sh_assign_3_fu_547_p3, "sh_assign_3_fu_547_p3");
    sc_trace(mVcdFile, sh_assign_3_i_cast_fu_555_p1, "sh_assign_3_i_cast_fu_555_p1");
    sc_trace(mVcdFile, tmp_i_i_i1_i_cast_fu_563_p1, "tmp_i_i_i1_i_cast_fu_563_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i7_i_cast_fu_515_p1, "tmp_7_i_i_i7_i_cast_fu_515_p1");
    sc_trace(mVcdFile, tmp_i_i_i1_i_fu_559_p1, "tmp_i_i_i1_i_fu_559_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i1_i_fu_567_p2, "tmp_1_i_i_i1_i_fu_567_p2");
    sc_trace(mVcdFile, tmp_26_fu_579_p3, "tmp_26_fu_579_p3");
    sc_trace(mVcdFile, tmp_3_i_i_i1_i_fu_573_p2, "tmp_3_i_i_i1_i_fu_573_p2");
    sc_trace(mVcdFile, tmp_15_fu_587_p1, "tmp_15_fu_587_p1");
    sc_trace(mVcdFile, tmp_16_fu_591_p4, "tmp_16_fu_591_p4");
    sc_trace(mVcdFile, loc_V_5_fu_623_p1, "loc_V_5_fu_623_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i_i1_fu_627_p4, "tmp_7_i_i_i_i1_fu_627_p4");
    sc_trace(mVcdFile, loc_V_4_fu_613_p4, "loc_V_4_fu_613_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i_i13_cast_fu_641_p1, "tmp_i_i_i_i_i13_cast_fu_641_p1");
    sc_trace(mVcdFile, sh_assign_4_fu_645_p2, "sh_assign_4_fu_645_p2");
    sc_trace(mVcdFile, tmp_9_i_i_i_i1_fu_659_p2, "tmp_9_i_i_i_i1_fu_659_p2");
    sc_trace(mVcdFile, isNeg_2_fu_651_p3, "isNeg_2_fu_651_p3");
    sc_trace(mVcdFile, tmp_9_i_i_i_i16_cast_fu_665_p1, "tmp_9_i_i_i_i16_cast_fu_665_p1");
    sc_trace(mVcdFile, sh_assign_5_fu_669_p3, "sh_assign_5_fu_669_p3");
    sc_trace(mVcdFile, sh_assign_1_i17_cast_fu_677_p1, "sh_assign_1_i17_cast_fu_677_p1");
    sc_trace(mVcdFile, tmp_i_i_i_i18_cast_fu_685_p1, "tmp_i_i_i_i18_cast_fu_685_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i_i12_cast_fu_637_p1, "tmp_7_i_i_i_i12_cast_fu_637_p1");
    sc_trace(mVcdFile, tmp_i_i_i_i1_fu_681_p1, "tmp_i_i_i_i1_fu_681_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i_i1_fu_689_p2, "tmp_1_i_i_i_i1_fu_689_p2");
    sc_trace(mVcdFile, tmp_33_fu_701_p3, "tmp_33_fu_701_p3");
    sc_trace(mVcdFile, tmp_3_i_i_i_i1_fu_695_p2, "tmp_3_i_i_i_i1_fu_695_p2");
    sc_trace(mVcdFile, tmp_17_fu_709_p1, "tmp_17_fu_709_p1");
    sc_trace(mVcdFile, tmp_19_fu_713_p4, "tmp_19_fu_713_p4");
    sc_trace(mVcdFile, loc_V_7_fu_745_p1, "loc_V_7_fu_745_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i7_i1_fu_749_p4, "tmp_7_i_i_i7_i1_fu_749_p4");
    sc_trace(mVcdFile, loc_V_6_fu_735_p4, "loc_V_6_fu_735_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i8_i34_cas_fu_763_p1, "tmp_i_i_i_i8_i34_cas_fu_763_p1");
    sc_trace(mVcdFile, sh_assign_6_fu_767_p2, "sh_assign_6_fu_767_p2");
    sc_trace(mVcdFile, tmp_9_i_i_i1_i1_fu_781_p2, "tmp_9_i_i_i1_i1_fu_781_p2");
    sc_trace(mVcdFile, isNeg_3_fu_773_p3, "isNeg_3_fu_773_p3");
    sc_trace(mVcdFile, tmp_9_i_i_i1_i37_cas_fu_787_p1, "tmp_9_i_i_i1_i37_cas_fu_787_p1");
    sc_trace(mVcdFile, sh_assign_7_fu_791_p3, "sh_assign_7_fu_791_p3");
    sc_trace(mVcdFile, sh_assign_3_i38_cast_fu_799_p1, "sh_assign_3_i38_cast_fu_799_p1");
    sc_trace(mVcdFile, tmp_i_i_i1_i39_cast_fu_807_p1, "tmp_i_i_i1_i39_cast_fu_807_p1");
    sc_trace(mVcdFile, tmp_7_i_i_i7_i33_cas_fu_759_p1, "tmp_7_i_i_i7_i33_cas_fu_759_p1");
    sc_trace(mVcdFile, tmp_i_i_i1_i1_fu_803_p1, "tmp_i_i_i1_i1_fu_803_p1");
    sc_trace(mVcdFile, tmp_1_i_i_i1_i1_fu_811_p2, "tmp_1_i_i_i1_i1_fu_811_p2");
    sc_trace(mVcdFile, tmp_37_fu_823_p3, "tmp_37_fu_823_p3");
    sc_trace(mVcdFile, tmp_3_i_i_i1_i1_fu_817_p2, "tmp_3_i_i_i1_i1_fu_817_p2");
    sc_trace(mVcdFile, tmp_20_fu_831_p1, "tmp_20_fu_831_p1");
    sc_trace(mVcdFile, tmp_21_fu_835_p4, "tmp_21_fu_835_p4");
    sc_trace(mVcdFile, p_Result_s_fu_853_p3, "p_Result_s_fu_853_p3");
    sc_trace(mVcdFile, p_Val2_6_i_i_i_i_fu_860_p2, "p_Val2_6_i_i_i_i_fu_860_p2");
    sc_trace(mVcdFile, p_Result_1_fu_872_p3, "p_Result_1_fu_872_p3");
    sc_trace(mVcdFile, p_Val2_6_i_i_i1_i_fu_879_p2, "p_Val2_6_i_i_i1_i_fu_879_p2");
    sc_trace(mVcdFile, p_Val2_4_fu_865_p3, "p_Val2_4_fu_865_p3");
    sc_trace(mVcdFile, p_Val2_9_fu_884_p3, "p_Val2_9_fu_884_p3");
    sc_trace(mVcdFile, p_Result_2_fu_899_p3, "p_Result_2_fu_899_p3");
    sc_trace(mVcdFile, p_Val2_6_i_i_i_i1_fu_906_p2, "p_Val2_6_i_i_i_i1_fu_906_p2");
    sc_trace(mVcdFile, p_Result_3_fu_918_p3, "p_Result_3_fu_918_p3");
    sc_trace(mVcdFile, p_Val2_6_i_i_i1_i1_fu_925_p2, "p_Val2_6_i_i_i1_i1_fu_925_p2");
    sc_trace(mVcdFile, p_Val2_14_fu_911_p3, "p_Val2_14_fu_911_p3");
    sc_trace(mVcdFile, p_Val2_19_fu_930_p3, "p_Val2_19_fu_930_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("dda.hdltvin.dat");
    mHdltvoutHandle.open("dda.hdltvout.dat");
}

dda::~dda() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete dda_fadd_32ns_32nbkb_U1;
    delete dda_fadd_32ns_32nbkb_U2;
    delete dda_fdiv_32ns_32ncud_U3;
    delete dda_fdiv_32ns_32ncud_U4;
    delete dda_sitofp_32ns_3dEe_U5;
    delete dda_sitofp_32ns_3dEe_U6;
    delete dda_sitofp_32ns_3dEe_U7;
    delete dda_fpext_32ns_64eOg_U8;
    delete dda_fpext_32ns_64eOg_U9;
    delete dda_fcmp_32ns_32nfYi_U10;
    delete dda_fcmp_32ns_32nfYi_U11;
    delete dda_dadd_64ns_64ng8j_U12;
    delete dda_dadd_64ns_64ng8j_U13;
}

void dda::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dda::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_0;
}

void dda::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_4;
}

void dda::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        i_reg_132 = i_1_reg_1016.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        i_reg_132 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        x_assign_3_reg_122 = Y_1_reg_1046.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        x_assign_3_reg_122 = Y_reg_998.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        x_assign_reg_112 = X_1_reg_1041.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        x_assign_reg_112 = X_reg_993.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        X_1_reg_1041 = grp_fu_143_p2.read();
        Y_1_reg_1046 = grp_fu_148_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        X_reg_993 = grp_fu_161_p1.read();
        Y_reg_998 = grp_fu_164_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        Xinc_reg_1003 = grp_fu_153_p2.read();
        Yinc_reg_1008 = grp_fu_157_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        dx_reg_955 = dx_fu_210_p2.read();
        dy_reg_963 = dy_fu_216_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        i_1_reg_1016 = i_1_fu_275_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_reg_1031.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()))) {
        p_Val2_10_reg_1073 = p_Val2_10_fu_609_p1.read();
        p_Val2_12_reg_1078 = p_Val2_12_fu_723_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_reg_1031.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()))) {
        p_Val2_15_reg_1084 = p_Val2_15_fu_731_p1.read();
        p_Val2_17_reg_1089 = p_Val2_17_fu_845_p3.read();
    }
    if ((esl_seteq<1,1,1>(tmp_4_reg_1021.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()))) {
        p_Val2_2_reg_1056 = p_Val2_2_fu_479_p3.read();
        p_Val2_s_reg_1051 = p_Val2_s_fu_365_p1.read();
    }
    if ((esl_seteq<1,1,1>(tmp_4_reg_1021.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()))) {
        p_Val2_5_reg_1062 = p_Val2_5_fu_487_p1.read();
        p_Val2_7_reg_1067 = p_Val2_7_fu_601_p3.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
  esl_seteq<1,1,1>(tmp_4_reg_1021.read(), ap_const_lv1_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
  esl_seteq<1,1,1>(tmp_4_reg_1021.read(), ap_const_lv1_0)))) {
        reg_202 = grp_fu_190_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_reg_1031.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_reg_1031.read())))) {
        reg_206 = grp_fu_196_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        steps_reg_971 = steps_fu_262_p3.read();
    }
    if ((esl_seteq<1,1,1>(tmp_9_fu_270_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        tmp_13_reg_1031 = tmp_13_fu_359_p2.read();
        tmp_1_i4_reg_1036 = tmp_1_i4_fu_174_p1.read();
        tmp_1_i_reg_1026 = tmp_1_i_fu_170_p1.read();
        tmp_4_reg_1021 = tmp_4_fu_317_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_6_reg_977 = grp_fu_161_p1.read();
        tmp_7_reg_982 = grp_fu_164_p1.read();
        tmp_8_reg_988 = grp_fu_167_p1.read();
    }
}

void dda::thread_X1_to_int_fu_281_p1() {
    X1_to_int_fu_281_p1 = x_assign_reg_112.read();
}

void dda::thread_Y1_to_int_fu_323_p1() {
    Y1_to_int_fu_323_p1 = x_assign_3_reg_122.read();
}

void dda::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dda::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dda::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void dda::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void dda::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dda::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void dda::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void dda::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void dda::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void dda::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void dda::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void dda::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dda::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dda::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void dda::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_9_fu_270_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dda::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dda::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_9_fu_270_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dda::thread_dx_fu_210_p2() {
    dx_fu_210_p2 = (!x1.read().is_01() || !x0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(x1.read()) - sc_biguint<32>(x0.read()));
}

void dda::thread_dy_fu_216_p2() {
    dy_fu_216_p2 = (!y1.read().is_01() || !y0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(y1.read()) - sc_biguint<32>(y0.read()));
}

void dda::thread_grp_fu_161_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_161_p0 = x0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_161_p0 = dx_reg_955.read();
    } else {
        grp_fu_161_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dda::thread_grp_fu_164_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_164_p0 = y0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_164_p0 = steps_reg_971.read();
    } else {
        grp_fu_164_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dda::thread_grp_fu_190_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        if (esl_seteq<1,1,1>(tmp_4_reg_1021.read(), ap_const_lv1_0)) {
            grp_fu_190_p1 = ap_const_lv64_3FE0000000000000;
        } else if (esl_seteq<1,1,1>(tmp_4_reg_1021.read(), ap_const_lv1_1)) {
            grp_fu_190_p1 = ap_const_lv64_BFE0000000000000;
        } else {
            grp_fu_190_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_fu_190_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dda::thread_grp_fu_196_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_reg_1031.read())) {
            grp_fu_196_p1 = ap_const_lv64_3FE0000000000000;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_13_reg_1031.read())) {
            grp_fu_196_p1 = ap_const_lv64_BFE0000000000000;
        } else {
            grp_fu_196_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_fu_196_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dda::thread_i_1_fu_275_p2() {
    i_1_fu_275_p2 = (!i_reg_132.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_reg_132.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void dda::thread_isNeg_1_fu_529_p3() {
    isNeg_1_fu_529_p3 = sh_assign_2_fu_523_p2.read().range(11, 11);
}

void dda::thread_isNeg_2_fu_651_p3() {
    isNeg_2_fu_651_p3 = sh_assign_4_fu_645_p2.read().range(11, 11);
}

void dda::thread_isNeg_3_fu_773_p3() {
    isNeg_3_fu_773_p3 = sh_assign_6_fu_767_p2.read().range(11, 11);
}

void dda::thread_isNeg_fu_407_p3() {
    isNeg_fu_407_p3 = sh_assign_fu_401_p2.read().range(11, 11);
}

void dda::thread_loc_V_1_fu_379_p1() {
    loc_V_1_fu_379_p1 = p_Val2_s_fu_365_p1.read().range(52-1, 0);
}

void dda::thread_loc_V_2_fu_491_p4() {
    loc_V_2_fu_491_p4 = p_Val2_5_fu_487_p1.read().range(62, 52);
}

void dda::thread_loc_V_3_fu_501_p1() {
    loc_V_3_fu_501_p1 = p_Val2_5_fu_487_p1.read().range(52-1, 0);
}

void dda::thread_loc_V_4_fu_613_p4() {
    loc_V_4_fu_613_p4 = p_Val2_10_fu_609_p1.read().range(62, 52);
}

void dda::thread_loc_V_5_fu_623_p1() {
    loc_V_5_fu_623_p1 = p_Val2_10_fu_609_p1.read().range(52-1, 0);
}

void dda::thread_loc_V_6_fu_735_p4() {
    loc_V_6_fu_735_p4 = p_Val2_15_fu_731_p1.read().range(62, 52);
}

void dda::thread_loc_V_7_fu_745_p1() {
    loc_V_7_fu_745_p1 = p_Val2_15_fu_731_p1.read().range(52-1, 0);
}

void dda::thread_loc_V_fu_369_p4() {
    loc_V_fu_369_p4 = p_Val2_s_fu_365_p1.read().range(62, 52);
}

void dda::thread_n_assign_1_fu_232_p3() {
    n_assign_1_fu_232_p3 = (!tmp_i_fu_222_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_i_fu_222_p2.read()[0].to_bool())? dx_reg_955.read(): tmp_i_8_fu_227_p2.read());
}

void dda::thread_n_assign_3_fu_249_p3() {
    n_assign_3_fu_249_p3 = (!tmp_i1_fu_239_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_i1_fu_239_p2.read()[0].to_bool())? dy_reg_963.read(): tmp_i2_fu_244_p2.read());
}

void dda::thread_notlhs1_fu_341_p2() {
    notlhs1_fu_341_p2 = (!tmp_s_fu_327_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_fu_327_p4.read() != ap_const_lv8_FF);
}

void dda::thread_notlhs_fu_299_p2() {
    notlhs_fu_299_p2 = (!tmp_fu_285_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_285_p4.read() != ap_const_lv8_FF);
}

void dda::thread_notrhs1_fu_347_p2() {
    notrhs1_fu_347_p2 = (!tmp_27_fu_337_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_27_fu_337_p1.read() == ap_const_lv23_0);
}

void dda::thread_notrhs_fu_305_p2() {
    notrhs_fu_305_p2 = (!tmp_1_fu_295_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_295_p1.read() == ap_const_lv23_0);
}

void dda::thread_p_Result_1_fu_872_p3() {
    p_Result_1_fu_872_p3 = p_Val2_5_reg_1062.read().range(63, 63);
}

void dda::thread_p_Result_2_fu_899_p3() {
    p_Result_2_fu_899_p3 = p_Val2_10_reg_1073.read().range(63, 63);
}

void dda::thread_p_Result_3_fu_918_p3() {
    p_Result_3_fu_918_p3 = p_Val2_15_reg_1084.read().range(63, 63);
}

void dda::thread_p_Result_s_fu_853_p3() {
    p_Result_s_fu_853_p3 = p_Val2_s_reg_1051.read().range(63, 63);
}

void dda::thread_p_Val2_10_fu_609_p1() {
    p_Val2_10_fu_609_p1 = reg_206.read();
}

void dda::thread_p_Val2_12_fu_723_p3() {
    p_Val2_12_fu_723_p3 = (!isNeg_2_fu_651_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_2_fu_651_p3.read()[0].to_bool())? tmp_17_fu_709_p1.read(): tmp_19_fu_713_p4.read());
}

void dda::thread_p_Val2_14_fu_911_p3() {
    p_Val2_14_fu_911_p3 = (!p_Result_2_fu_899_p3.read()[0].is_01())? sc_lv<32>(): ((p_Result_2_fu_899_p3.read()[0].to_bool())? p_Val2_6_i_i_i_i1_fu_906_p2.read(): p_Val2_12_reg_1078.read());
}

void dda::thread_p_Val2_15_fu_731_p1() {
    p_Val2_15_fu_731_p1 = reg_206.read();
}

void dda::thread_p_Val2_17_fu_845_p3() {
    p_Val2_17_fu_845_p3 = (!isNeg_3_fu_773_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_3_fu_773_p3.read()[0].to_bool())? tmp_20_fu_831_p1.read(): tmp_21_fu_835_p4.read());
}

void dda::thread_p_Val2_19_fu_930_p3() {
    p_Val2_19_fu_930_p3 = (!p_Result_3_fu_918_p3.read()[0].is_01())? sc_lv<32>(): ((p_Result_3_fu_918_p3.read()[0].to_bool())? p_Val2_6_i_i_i1_i1_fu_925_p2.read(): p_Val2_17_reg_1089.read());
}

void dda::thread_p_Val2_2_fu_479_p3() {
    p_Val2_2_fu_479_p3 = (!isNeg_fu_407_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_407_p3.read()[0].to_bool())? tmp_10_fu_465_p1.read(): tmp_14_fu_469_p4.read());
}

void dda::thread_p_Val2_4_fu_865_p3() {
    p_Val2_4_fu_865_p3 = (!p_Result_s_fu_853_p3.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_fu_853_p3.read()[0].to_bool())? p_Val2_6_i_i_i_i_fu_860_p2.read(): p_Val2_2_reg_1056.read());
}

void dda::thread_p_Val2_5_fu_487_p1() {
    p_Val2_5_fu_487_p1 = reg_202.read();
}

void dda::thread_p_Val2_6_i_i_i1_i1_fu_925_p2() {
    p_Val2_6_i_i_i1_i1_fu_925_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_17_reg_1089.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_17_reg_1089.read()));
}

void dda::thread_p_Val2_6_i_i_i1_i_fu_879_p2() {
    p_Val2_6_i_i_i1_i_fu_879_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_7_reg_1067.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_7_reg_1067.read()));
}

void dda::thread_p_Val2_6_i_i_i_i1_fu_906_p2() {
    p_Val2_6_i_i_i_i1_fu_906_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_12_reg_1078.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_12_reg_1078.read()));
}

void dda::thread_p_Val2_6_i_i_i_i_fu_860_p2() {
    p_Val2_6_i_i_i_i_fu_860_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_2_reg_1056.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_2_reg_1056.read()));
}

void dda::thread_p_Val2_7_fu_601_p3() {
    p_Val2_7_fu_601_p3 = (!isNeg_1_fu_529_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_1_fu_529_p3.read()[0].to_bool())? tmp_15_fu_587_p1.read(): tmp_16_fu_591_p4.read());
}

void dda::thread_p_Val2_9_fu_884_p3() {
    p_Val2_9_fu_884_p3 = (!p_Result_1_fu_872_p3.read()[0].is_01())? sc_lv<32>(): ((p_Result_1_fu_872_p3.read()[0].to_bool())? p_Val2_6_i_i_i1_i_fu_879_p2.read(): p_Val2_7_reg_1067.read());
}

void dda::thread_p_Val2_s_fu_365_p1() {
    p_Val2_s_fu_365_p1 = reg_202.read();
}

void dda::thread_sh_assign_1_fu_425_p3() {
    sh_assign_1_fu_425_p3 = (!isNeg_fu_407_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_407_p3.read()[0].to_bool())? tmp_9_i_i_i_i_cast_fu_421_p1.read(): sh_assign_fu_401_p2.read());
}

void dda::thread_sh_assign_1_i17_cast_fu_677_p1() {
    sh_assign_1_i17_cast_fu_677_p1 = esl_sext<32,12>(sh_assign_5_fu_669_p3.read());
}

void dda::thread_sh_assign_1_i_cast_fu_433_p1() {
    sh_assign_1_i_cast_fu_433_p1 = esl_sext<32,12>(sh_assign_1_fu_425_p3.read());
}

void dda::thread_sh_assign_2_fu_523_p2() {
    sh_assign_2_fu_523_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i8_i_cast_fu_519_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i8_i_cast_fu_519_p1.read()));
}

void dda::thread_sh_assign_3_fu_547_p3() {
    sh_assign_3_fu_547_p3 = (!isNeg_1_fu_529_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_1_fu_529_p3.read()[0].to_bool())? tmp_9_i_i_i1_i_cast_fu_543_p1.read(): sh_assign_2_fu_523_p2.read());
}

void dda::thread_sh_assign_3_i38_cast_fu_799_p1() {
    sh_assign_3_i38_cast_fu_799_p1 = esl_sext<32,12>(sh_assign_7_fu_791_p3.read());
}

void dda::thread_sh_assign_3_i_cast_fu_555_p1() {
    sh_assign_3_i_cast_fu_555_p1 = esl_sext<32,12>(sh_assign_3_fu_547_p3.read());
}

void dda::thread_sh_assign_4_fu_645_p2() {
    sh_assign_4_fu_645_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i_i13_cast_fu_641_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i_i13_cast_fu_641_p1.read()));
}

void dda::thread_sh_assign_5_fu_669_p3() {
    sh_assign_5_fu_669_p3 = (!isNeg_2_fu_651_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_2_fu_651_p3.read()[0].to_bool())? tmp_9_i_i_i_i16_cast_fu_665_p1.read(): sh_assign_4_fu_645_p2.read());
}

void dda::thread_sh_assign_6_fu_767_p2() {
    sh_assign_6_fu_767_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i8_i34_cas_fu_763_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i8_i34_cas_fu_763_p1.read()));
}

void dda::thread_sh_assign_7_fu_791_p3() {
    sh_assign_7_fu_791_p3 = (!isNeg_3_fu_773_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_3_fu_773_p3.read()[0].to_bool())? tmp_9_i_i_i1_i37_cas_fu_787_p1.read(): sh_assign_6_fu_767_p2.read());
}

void dda::thread_sh_assign_fu_401_p2() {
    sh_assign_fu_401_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i_i_cast_fu_397_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i_i_cast_fu_397_p1.read()));
}

void dda::thread_steps_fu_262_p3() {
    steps_fu_262_p3 = (!tmp_5_fu_256_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_256_p2.read()[0].to_bool())? n_assign_1_fu_232_p3.read(): n_assign_3_fu_249_p3.read());
}

void dda::thread_tmp_10_fu_465_p1() {
    tmp_10_fu_465_p1 = esl_zext<32,1>(tmp_18_fu_457_p3.read());
}

void dda::thread_tmp_11_fu_353_p2() {
    tmp_11_fu_353_p2 = (notrhs1_fu_347_p2.read() | notlhs1_fu_341_p2.read());
}

void dda::thread_tmp_13_fu_359_p2() {
    tmp_13_fu_359_p2 = (tmp_11_fu_353_p2.read() & tmp_12_fu_184_p2.read());
}

void dda::thread_tmp_14_fu_469_p4() {
    tmp_14_fu_469_p4 = tmp_3_i_i_i_i_fu_451_p2.read().range(84, 53);
}

void dda::thread_tmp_15_fu_587_p1() {
    tmp_15_fu_587_p1 = esl_zext<32,1>(tmp_26_fu_579_p3.read());
}

void dda::thread_tmp_16_fu_591_p4() {
    tmp_16_fu_591_p4 = tmp_3_i_i_i1_i_fu_573_p2.read().range(84, 53);
}

void dda::thread_tmp_17_fu_709_p1() {
    tmp_17_fu_709_p1 = esl_zext<32,1>(tmp_33_fu_701_p3.read());
}

void dda::thread_tmp_18_fu_457_p3() {
    tmp_18_fu_457_p3 = tmp_1_i_i_i_i_fu_445_p2.read().range(53, 53);
}

void dda::thread_tmp_19_fu_713_p4() {
    tmp_19_fu_713_p4 = tmp_3_i_i_i_i1_fu_695_p2.read().range(84, 53);
}

void dda::thread_tmp_1_fu_295_p1() {
    tmp_1_fu_295_p1 = X1_to_int_fu_281_p1.read().range(23-1, 0);
}

void dda::thread_tmp_1_i_i_i1_i1_fu_811_p2() {
    tmp_1_i_i_i1_i1_fu_811_p2 = (!tmp_i_i_i1_i39_cast_fu_807_p1.read().is_01())? sc_lv<54>(): tmp_7_i_i_i7_i1_fu_749_p4.read() >> (unsigned short)tmp_i_i_i1_i39_cast_fu_807_p1.read().to_uint();
}

void dda::thread_tmp_1_i_i_i1_i_fu_567_p2() {
    tmp_1_i_i_i1_i_fu_567_p2 = (!tmp_i_i_i1_i_cast_fu_563_p1.read().is_01())? sc_lv<54>(): tmp_7_i_i_i7_i_fu_505_p4.read() >> (unsigned short)tmp_i_i_i1_i_cast_fu_563_p1.read().to_uint();
}

void dda::thread_tmp_1_i_i_i_i1_fu_689_p2() {
    tmp_1_i_i_i_i1_fu_689_p2 = (!tmp_i_i_i_i18_cast_fu_685_p1.read().is_01())? sc_lv<54>(): tmp_7_i_i_i_i1_fu_627_p4.read() >> (unsigned short)tmp_i_i_i_i18_cast_fu_685_p1.read().to_uint();
}

void dda::thread_tmp_1_i_i_i_i_fu_445_p2() {
    tmp_1_i_i_i_i_fu_445_p2 = (!tmp_i_i_i_i_cast_fu_441_p1.read().is_01())? sc_lv<54>(): tmp_7_i_i_i_i_fu_383_p4.read() >> (unsigned short)tmp_i_i_i_i_cast_fu_441_p1.read().to_uint();
}

void dda::thread_tmp_20_fu_831_p1() {
    tmp_20_fu_831_p1 = esl_zext<32,1>(tmp_37_fu_823_p3.read());
}

void dda::thread_tmp_21_fu_835_p4() {
    tmp_21_fu_835_p4 = tmp_3_i_i_i1_i1_fu_817_p2.read().range(84, 53);
}

void dda::thread_tmp_26_fu_579_p3() {
    tmp_26_fu_579_p3 = tmp_1_i_i_i1_i_fu_567_p2.read().range(53, 53);
}

void dda::thread_tmp_27_fu_337_p1() {
    tmp_27_fu_337_p1 = Y1_to_int_fu_323_p1.read().range(23-1, 0);
}

void dda::thread_tmp_2_fu_311_p2() {
    tmp_2_fu_311_p2 = (notrhs_fu_305_p2.read() | notlhs_fu_299_p2.read());
}

void dda::thread_tmp_33_fu_701_p3() {
    tmp_33_fu_701_p3 = tmp_1_i_i_i_i1_fu_689_p2.read().range(53, 53);
}

void dda::thread_tmp_37_fu_823_p3() {
    tmp_37_fu_823_p3 = tmp_1_i_i_i1_i1_fu_811_p2.read().range(53, 53);
}

void dda::thread_tmp_3_i_i_i1_i1_fu_817_p2() {
    tmp_3_i_i_i1_i1_fu_817_p2 = (!tmp_i_i_i1_i1_fu_803_p1.read().is_01())? sc_lv<137>(): tmp_7_i_i_i7_i33_cas_fu_759_p1.read() << (unsigned short)tmp_i_i_i1_i1_fu_803_p1.read().to_uint();
}

void dda::thread_tmp_3_i_i_i1_i_fu_573_p2() {
    tmp_3_i_i_i1_i_fu_573_p2 = (!tmp_i_i_i1_i_fu_559_p1.read().is_01())? sc_lv<137>(): tmp_7_i_i_i7_i_cast_fu_515_p1.read() << (unsigned short)tmp_i_i_i1_i_fu_559_p1.read().to_uint();
}

void dda::thread_tmp_3_i_i_i_i1_fu_695_p2() {
    tmp_3_i_i_i_i1_fu_695_p2 = (!tmp_i_i_i_i1_fu_681_p1.read().is_01())? sc_lv<137>(): tmp_7_i_i_i_i12_cast_fu_637_p1.read() << (unsigned short)tmp_i_i_i_i1_fu_681_p1.read().to_uint();
}

void dda::thread_tmp_3_i_i_i_i_fu_451_p2() {
    tmp_3_i_i_i_i_fu_451_p2 = (!tmp_i_i_i_i_fu_437_p1.read().is_01())? sc_lv<137>(): tmp_7_i_i_i_i_cast_fu_393_p1.read() << (unsigned short)tmp_i_i_i_i_fu_437_p1.read().to_uint();
}

void dda::thread_tmp_4_fu_317_p2() {
    tmp_4_fu_317_p2 = (tmp_2_fu_311_p2.read() & tmp_3_fu_178_p2.read());
}

void dda::thread_tmp_5_fu_256_p2() {
    tmp_5_fu_256_p2 = (!n_assign_1_fu_232_p3.read().is_01() || !n_assign_3_fu_249_p3.read().is_01())? sc_lv<1>(): (sc_bigint<32>(n_assign_1_fu_232_p3.read()) > sc_bigint<32>(n_assign_3_fu_249_p3.read()));
}

void dda::thread_tmp_7_i_i_i7_i1_fu_749_p4() {
    tmp_7_i_i_i7_i1_fu_749_p4 = esl_concat<53,1>(esl_concat<1,52>(ap_const_lv1_1, loc_V_7_fu_745_p1.read()), ap_const_lv1_0);
}

void dda::thread_tmp_7_i_i_i7_i33_cas_fu_759_p1() {
    tmp_7_i_i_i7_i33_cas_fu_759_p1 = esl_zext<137,54>(tmp_7_i_i_i7_i1_fu_749_p4.read());
}

void dda::thread_tmp_7_i_i_i7_i_cast_fu_515_p1() {
    tmp_7_i_i_i7_i_cast_fu_515_p1 = esl_zext<137,54>(tmp_7_i_i_i7_i_fu_505_p4.read());
}

void dda::thread_tmp_7_i_i_i7_i_fu_505_p4() {
    tmp_7_i_i_i7_i_fu_505_p4 = esl_concat<53,1>(esl_concat<1,52>(ap_const_lv1_1, loc_V_3_fu_501_p1.read()), ap_const_lv1_0);
}

void dda::thread_tmp_7_i_i_i_i12_cast_fu_637_p1() {
    tmp_7_i_i_i_i12_cast_fu_637_p1 = esl_zext<137,54>(tmp_7_i_i_i_i1_fu_627_p4.read());
}

void dda::thread_tmp_7_i_i_i_i1_fu_627_p4() {
    tmp_7_i_i_i_i1_fu_627_p4 = esl_concat<53,1>(esl_concat<1,52>(ap_const_lv1_1, loc_V_5_fu_623_p1.read()), ap_const_lv1_0);
}

void dda::thread_tmp_7_i_i_i_i_cast_fu_393_p1() {
    tmp_7_i_i_i_i_cast_fu_393_p1 = esl_zext<137,54>(tmp_7_i_i_i_i_fu_383_p4.read());
}

void dda::thread_tmp_7_i_i_i_i_fu_383_p4() {
    tmp_7_i_i_i_i_fu_383_p4 = esl_concat<53,1>(esl_concat<1,52>(ap_const_lv1_1, loc_V_1_fu_379_p1.read()), ap_const_lv1_0);
}

void dda::thread_tmp_9_fu_270_p2() {
    tmp_9_fu_270_p2 = (!i_reg_132.read().is_01() || !steps_reg_971.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_reg_132.read()) > sc_bigint<32>(steps_reg_971.read()));
}

void dda::thread_tmp_9_i_i_i1_i1_fu_781_p2() {
    tmp_9_i_i_i1_i1_fu_781_p2 = (!ap_const_lv11_3FF.is_01() || !loc_V_6_fu_735_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(loc_V_6_fu_735_p4.read()));
}

void dda::thread_tmp_9_i_i_i1_i37_cas_fu_787_p1() {
    tmp_9_i_i_i1_i37_cas_fu_787_p1 = esl_sext<12,11>(tmp_9_i_i_i1_i1_fu_781_p2.read());
}

void dda::thread_tmp_9_i_i_i1_i_cast_fu_543_p1() {
    tmp_9_i_i_i1_i_cast_fu_543_p1 = esl_sext<12,11>(tmp_9_i_i_i1_i_fu_537_p2.read());
}

void dda::thread_tmp_9_i_i_i1_i_fu_537_p2() {
    tmp_9_i_i_i1_i_fu_537_p2 = (!ap_const_lv11_3FF.is_01() || !loc_V_2_fu_491_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(loc_V_2_fu_491_p4.read()));
}

void dda::thread_tmp_9_i_i_i_i16_cast_fu_665_p1() {
    tmp_9_i_i_i_i16_cast_fu_665_p1 = esl_sext<12,11>(tmp_9_i_i_i_i1_fu_659_p2.read());
}

void dda::thread_tmp_9_i_i_i_i1_fu_659_p2() {
    tmp_9_i_i_i_i1_fu_659_p2 = (!ap_const_lv11_3FF.is_01() || !loc_V_4_fu_613_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(loc_V_4_fu_613_p4.read()));
}

void dda::thread_tmp_9_i_i_i_i_cast_fu_421_p1() {
    tmp_9_i_i_i_i_cast_fu_421_p1 = esl_sext<12,11>(tmp_9_i_i_i_i_fu_415_p2.read());
}

void dda::thread_tmp_9_i_i_i_i_fu_415_p2() {
    tmp_9_i_i_i_i_fu_415_p2 = (!ap_const_lv11_3FF.is_01() || !loc_V_fu_369_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(loc_V_fu_369_p4.read()));
}

void dda::thread_tmp_fu_285_p4() {
    tmp_fu_285_p4 = X1_to_int_fu_281_p1.read().range(30, 23);
}

void dda::thread_tmp_i1_fu_239_p2() {
    tmp_i1_fu_239_p2 = (!dy_reg_963.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(dy_reg_963.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void dda::thread_tmp_i2_fu_244_p2() {
    tmp_i2_fu_244_p2 = (!ap_const_lv32_0.is_01() || !dy_reg_963.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(dy_reg_963.read()));
}

void dda::thread_tmp_i_8_fu_227_p2() {
    tmp_i_8_fu_227_p2 = (!ap_const_lv32_0.is_01() || !dx_reg_955.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(dx_reg_955.read()));
}

void dda::thread_tmp_i_fu_222_p2() {
    tmp_i_fu_222_p2 = (!dx_reg_955.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(dx_reg_955.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void dda::thread_tmp_i_i_i1_i1_fu_803_p1() {
    tmp_i_i_i1_i1_fu_803_p1 = esl_zext<137,32>(sh_assign_3_i38_cast_fu_799_p1.read());
}

void dda::thread_tmp_i_i_i1_i39_cast_fu_807_p1() {
    tmp_i_i_i1_i39_cast_fu_807_p1 = esl_zext<54,32>(sh_assign_3_i38_cast_fu_799_p1.read());
}

void dda::thread_tmp_i_i_i1_i_cast_fu_563_p1() {
    tmp_i_i_i1_i_cast_fu_563_p1 = esl_zext<54,32>(sh_assign_3_i_cast_fu_555_p1.read());
}

void dda::thread_tmp_i_i_i1_i_fu_559_p1() {
    tmp_i_i_i1_i_fu_559_p1 = esl_zext<137,32>(sh_assign_3_i_cast_fu_555_p1.read());
}

void dda::thread_tmp_i_i_i_i18_cast_fu_685_p1() {
    tmp_i_i_i_i18_cast_fu_685_p1 = esl_zext<54,32>(sh_assign_1_i17_cast_fu_677_p1.read());
}

void dda::thread_tmp_i_i_i_i1_fu_681_p1() {
    tmp_i_i_i_i1_fu_681_p1 = esl_zext<137,32>(sh_assign_1_i17_cast_fu_677_p1.read());
}

void dda::thread_tmp_i_i_i_i8_i34_cas_fu_763_p1() {
    tmp_i_i_i_i8_i34_cas_fu_763_p1 = esl_zext<12,11>(loc_V_6_fu_735_p4.read());
}

void dda::thread_tmp_i_i_i_i8_i_cast_fu_519_p1() {
    tmp_i_i_i_i8_i_cast_fu_519_p1 = esl_zext<12,11>(loc_V_2_fu_491_p4.read());
}

void dda::thread_tmp_i_i_i_i_cast_fu_441_p1() {
    tmp_i_i_i_i_cast_fu_441_p1 = esl_zext<54,32>(sh_assign_1_i_cast_fu_433_p1.read());
}

void dda::thread_tmp_i_i_i_i_fu_437_p1() {
    tmp_i_i_i_i_fu_437_p1 = esl_zext<137,32>(sh_assign_1_i_cast_fu_433_p1.read());
}

void dda::thread_tmp_i_i_i_i_i13_cast_fu_641_p1() {
    tmp_i_i_i_i_i13_cast_fu_641_p1 = esl_zext<12,11>(loc_V_4_fu_613_p4.read());
}

void dda::thread_tmp_i_i_i_i_i_cast_fu_397_p1() {
    tmp_i_i_i_i_i_cast_fu_397_p1 = esl_zext<12,11>(loc_V_fu_369_p4.read());
}

void dda::thread_tmp_s_fu_327_p4() {
    tmp_s_fu_327_p4 = Y1_to_int_fu_323_p1.read().range(30, 23);
}

void dda::thread_xp() {
    xp = (!tmp_4_reg_1021.read()[0].is_01())? sc_lv<32>(): ((tmp_4_reg_1021.read()[0].to_bool())? p_Val2_4_fu_865_p3.read(): p_Val2_9_fu_884_p3.read());
}

void dda::thread_xp_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        xp_ap_vld = ap_const_logic_1;
    } else {
        xp_ap_vld = ap_const_logic_0;
    }
}

void dda::thread_yp() {
    yp = (!tmp_13_reg_1031.read()[0].is_01())? sc_lv<32>(): ((tmp_13_reg_1031.read()[0].to_bool())? p_Val2_14_fu_911_p3.read(): p_Val2_19_fu_930_p3.read());
}

void dda::thread_yp_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        yp_ap_vld = ap_const_logic_1;
    } else {
        yp_ap_vld = ap_const_logic_0;
    }
}

void dda::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(tmp_9_fu_270_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<28>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void dda::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x0\" :  \"" << x0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"y0\" :  \"" << y0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x1\" :  \"" << x1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"y1\" :  \"" << y1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xp\" :  \"" << xp.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"xp_ap_vld\" :  \"" << xp_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"yp\" :  \"" << yp.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"yp_ap_vld\" :  \"" << yp_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

